import { useLogout, useGetIdentity } from "@refinedev/core";
import type { ReactNode } from "react";
import { Outlet } from "react-router-dom";

import { CommandPalette } from "../components/kit/CommandPalette";
import { Header } from "./Header";
import { navGroups } from "./nav";
import "./shell.css";
import { Sidebar } from "./Sidebar";

// A1-T2: the shell rebuilt on the admin kit. Sidebar/Header/nav.ts/
// ThemeToggle extracted out of this file so each piece is independently
// testable and the command palette can share the same nav data. Every
// value here reads a CSS var from tokens.css (generated by
// scripts/gen-tokens.ts from @atlitos/theme), never a raw hex, so the lint
// no-hex rule and CLAUDE.md "Tokens only" both pass. Login page untouched
// per Part B plan (its own font-family swap is the one exception, A1-T1).
export function Shell(): ReactNode {
  const { mutate: logout } = useLogout();
  const { data: identity } = useGetIdentity<{ id: string; name?: string | null }>();

  return (
    <div className="ak-shell">
      <Sidebar identityName={identity?.name} onLogout={() => logout()} />
      <div className="ak-shell-body">
        <Header />
        <main className="ak-shell-main">
          <Outlet />
        </main>
      </div>
      <CommandPalette groups={navGroups} />
    </div>
  );
}
