import { useLogout, useGetIdentity } from "@refinedev/core";
import { Building2, CalendarClock, LayoutGrid, LogOut, Percent, ShieldCheck, Users } from "lucide-react";
import type { ReactNode } from "react";
import { NavLink, Outlet } from "react-router-dom";

// Restyled minimally toward docs/design/DESIGN-LANGUAGE.md: warm light
// sidebar (colors.light.surface on colors.light.bg), ember accent
// (--color-accent, generated by scripts/gen-tokens.ts from @atlitos/theme,
// see src/styles/tokens.css) for the active nav item and brand mark. Every
// value here reads a CSS var from that generated sheet, never a raw hex, so
// the lint no-hex rule and CLAUDE.md "Tokens only" both pass.
const navItems = [
  { to: "/verification", label: "Verification queue", icon: ShieldCheck },
  { to: "/venues", label: "Venues", icon: Building2 },
  { to: "/bookings", label: "Bookings", icon: CalendarClock },
  { to: "/fee-config", label: "Fee config", icon: Percent },
  { to: "/users", label: "Users", icon: Users },
];

function NavIcon({ icon: Icon }: { icon: typeof ShieldCheck }) {
  return <Icon size={20} strokeWidth={1.75} />;
}

export function Shell(): ReactNode {
  const { mutate: logout } = useLogout();
  const { data: identity } = useGetIdentity<{ id: string; name?: string | null }>();

  return (
    <div
      style={{
        minHeight: "100vh",
        display: "flex",
        backgroundColor: "var(--color-bg)",
        color: "var(--color-text)",
        fontFamily: "Inter, sans-serif",
      }}
    >
      <aside
        style={{
          width: 240,
          flexShrink: 0,
          display: "flex",
          flexDirection: "column",
          gap: "var(--space-lg)",
          padding: "var(--space-lg)",
          backgroundColor: "var(--color-surface)",
          borderRight: "1px solid var(--color-border)",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "var(--space-sm)",
            padding: "var(--space-sm) var(--space-xs)",
          }}
        >
          <span
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              width: 32,
              height: 32,
              borderRadius: "var(--radius-sm)",
              backgroundColor: "var(--color-accent)",
              color: "var(--color-ink-on-accent)",
            }}
          >
            <LayoutGrid size={20} strokeWidth={1.75} />
          </span>
          <span style={{ fontWeight: 700, fontSize: 18, letterSpacing: "-0.4px" }}>
            Atlitos Admin
          </span>
        </div>

        <nav style={{ display: "flex", flexDirection: "column", gap: "var(--space-xs)" }}>
          {navItems.map(({ to, label, icon }) => (
            <NavLink
              key={to}
              to={to}
              style={({ isActive }) => ({
                display: "flex",
                alignItems: "center",
                gap: "var(--space-sm)",
                padding: "var(--space-sm) var(--space-md)",
                borderRadius: "var(--radius-md)",
                textDecoration: "none",
                fontSize: 14,
                fontWeight: 600,
                color: isActive ? "var(--color-accent)" : "var(--color-text-secondary)",
                backgroundColor: isActive ? "var(--color-accent-tint)" : "transparent",
              })}
            >
              <NavIcon icon={icon} />
              {label}
            </NavLink>
          ))}
        </nav>

        <div style={{ flex: 1 }} />

        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: "var(--space-sm)",
            padding: "var(--space-sm) var(--space-xs)",
            borderTop: "1px solid var(--color-border)",
          }}
        >
          <span
            style={{
              fontSize: 13,
              color: "var(--color-text-secondary)",
              overflow: "hidden",
              textOverflow: "ellipsis",
              whiteSpace: "nowrap",
            }}
          >
            {identity?.name ?? "Signed in"}
          </span>
          <button
            type="button"
            onClick={() => logout()}
            style={{
              display: "flex",
              alignItems: "center",
              gap: "var(--space-sm)",
              padding: "var(--space-sm) var(--space-md)",
              borderRadius: "var(--radius-sm)",
              border: "1px solid var(--color-border-strong)",
              backgroundColor: "var(--color-surface)",
              color: "var(--color-text)",
              fontSize: 14,
              fontWeight: 600,
              cursor: "pointer",
            }}
          >
            <LogOut size={16} strokeWidth={1.75} />
            Sign out
          </button>
        </div>
      </aside>

      <main style={{ flex: 1, padding: "var(--space-2xl)", overflowY: "auto" }}>
        <Outlet />
      </main>
    </div>
  );
}
