import { TextClassContext } from '@/components/ui/text';
import { cn } from '@/lib/utils';
import { cva, type VariantProps } from 'class-variance-authority';
import type { ComponentProps } from 'react';
import { Pressable } from 'react-native';

/**
 * react-native-reusables Button, adapted to Atlitos tokens:
 * - radius.sm (rounded-sm, 8px) on every variant, the design language's
 *   locked CTA radius decision, not RNR's stock rounded-md.
 * - height 48 (h-12, Tailwind's native scale, 12 * 4px) for the default
 *   size, the locked mobile primary tap target from DESIGN-LANGUAGE.md;
 *   compact/sm uses 40 (h-10), matching the web/compact spec.
 * - every fill, text, and border color is a bg, text, or border utility
 *   generated by tailwind.config.js from @atlitos/theme (see
 *   scripts/gen-tokens.ts), never a raw hex or an un-namespaced Tailwind color.
 */
const buttonVariants = cva('flex-row items-center justify-center gap-sm rounded-sm', {
  variants: {
    variant: {
      default: 'bg-primary active:bg-accent-pressed',
      secondary: 'border border-border-strong bg-surface active:bg-surface-muted',
      destructive: 'bg-destructive active:opacity-90',
      outline: 'border border-border-strong bg-transparent active:bg-surface-muted',
      ghost: 'active:bg-surface-muted',
      link: '',
    },
    size: {
      default: 'h-12 px-lg py-sm',
      sm: 'h-10 gap-xs rounded-sm px-md',
      lg: 'h-12 rounded-sm px-2xl',
      icon: 'h-12 w-12',
    },
  },
  defaultVariants: {
    variant: 'default',
    size: 'default',
  },
});

const buttonTextVariants = cva('text-center font-sans-semibold text-base', {
  variants: {
    variant: {
      default: 'text-primary-foreground',
      secondary: 'text-text',
      destructive: 'text-primary-foreground',
      outline: 'text-text',
      ghost: 'text-text',
      link: 'text-accent underline',
    },
    size: {
      default: '',
      sm: '',
      lg: '',
      icon: '',
    },
  },
  defaultVariants: {
    variant: 'default',
    size: 'default',
  },
});

type ButtonProps = ComponentProps<typeof Pressable> & VariantProps<typeof buttonVariants>;

function Button({ className, variant, size, ...props }: ButtonProps) {
  return (
    <TextClassContext.Provider value={buttonTextVariants({ variant, size })}>
      <Pressable
        className={cn(props.disabled && 'opacity-50', buttonVariants({ variant, size }), className)}
        role="button"
        {...props}
      />
    </TextClassContext.Provider>
  );
}

export { Button, buttonTextVariants, buttonVariants };
export type { ButtonProps };
