// GENERATED by `supabase gen types typescript` (via the Supabase MCP
// generate_typescript_types tool) against the `atlitos` project
// (syzzfgaudpifwvbpycyi) after migrations 0001-0015 were applied. Covers
// identity/roles, notifications, moderation/audit, courts, and payments
// (0009_courts.sql through 0015_court_rating_summary.sql, Phase 2 courts
// vertical slice), plus every Phase 1 RPC. Every later domain migration
// (coaching, commerce, clutch, empower, learn, chat) regenerates this file
// wholesale when it lands; do not hand-edit it, re-run generation instead.
// `db/rows.ts` in this package documents the eventual full schema
// (including domains not yet migrated) and is what app code should still
// prefer importing from for domains this file does not cover yet.
//
// PHASE 2 INTEGRATION PASS NOTE: regenerated wholesale by the integrator
// after applying migrations 0009-0015 to the remote project. The previous
// hand-authored courts/payments section (added ahead of migrations landing)
// has been replaced by this real introspection; apps/portal-court's local
// `courts-database.types.ts` bridging file (whose own header called for its
// deletion at exactly this point) has been removed and its call sites now
// import `Database` from `@atlitos/types` directly.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      addresses: {
        Row: {
          city: string
          created_at: string
          id: string
          is_default: boolean
          line1: string
          line2: string | null
          pincode: string
          state: string
          user_id: string
        }
        Insert: {
          city: string
          created_at?: string
          id?: string
          is_default?: boolean
          line1: string
          line2?: string | null
          pincode: string
          state: string
          user_id: string
        }
        Update: {
          city?: string
          created_at?: string
          id?: string
          is_default?: boolean
          line1?: string
          line2?: string | null
          pincode?: string
          state?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "addresses_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "addresses_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      athlete_sports: {
        Row: {
          created_at: string
          id: string
          is_primary: boolean
          skill_level: string | null
          sport: Database["public"]["Enums"]["sport"]
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_primary?: boolean
          skill_level?: string | null
          sport: Database["public"]["Enums"]["sport"]
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          is_primary?: boolean
          skill_level?: string | null
          sport?: Database["public"]["Enums"]["sport"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "athlete_sports_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "athlete_sports_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          after: Json | null
          before: Json | null
          created_at: string
          entity_id: string
          entity_type: string
          id: string
          note: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          entity_id: string
          entity_type: string
          id?: string
          note?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          entity_id?: string
          entity_type?: string
          id?: string
          note?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      coach_certificates: {
        Row: {
          coach_id: string
          created_at: string
          id: string
          name: string
          storage_path: string
          verified: boolean
        }
        Insert: {
          coach_id: string
          created_at?: string
          id?: string
          name: string
          storage_path: string
          verified?: boolean
        }
        Update: {
          coach_id?: string
          created_at?: string
          id?: string
          name?: string
          storage_path?: string
          verified?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "coach_certificates_coach_id_fkey"
            columns: ["coach_id"]
            isOneToOne: false
            referencedRelation: "coach_profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "coach_certificates_coach_id_fkey"
            columns: ["coach_id"]
            isOneToOne: false
            referencedRelation: "coach_profiles_public"
            referencedColumns: ["user_id"]
          },
        ]
      }
      coach_profiles: {
        Row: {
          bio: string | null
          city: string
          coaching_style: string | null
          created_at: string
          experience_years: number
          players_coached_count: number
          rating: number
          rating_count: number
          specialization: string[]
          sport: Database["public"]["Enums"]["sport"]
          state: string
          status: Database["public"]["Enums"]["coach_status"]
          updated_at: string
          user_id: string
        }
        Insert: {
          bio?: string | null
          city: string
          coaching_style?: string | null
          created_at?: string
          experience_years: number
          players_coached_count?: number
          rating?: number
          rating_count?: number
          specialization?: string[]
          sport: Database["public"]["Enums"]["sport"]
          state: string
          status?: Database["public"]["Enums"]["coach_status"]
          updated_at?: string
          user_id: string
        }
        Update: {
          bio?: string | null
          city?: string
          coaching_style?: string | null
          created_at?: string
          experience_years?: number
          players_coached_count?: number
          rating?: number
          rating_count?: number
          specialization?: string[]
          sport?: Database["public"]["Enums"]["sport"]
          state?: string
          status?: Database["public"]["Enums"]["coach_status"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "coach_profiles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "coach_profiles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      court_availability_windows: {
        Row: {
          close_time: string
          court_id: string
          created_at: string
          day_of_week: number
          id: string
          open_time: string
          slot_duration_minutes: number
        }
        Insert: {
          close_time: string
          court_id: string
          created_at?: string
          day_of_week: number
          id?: string
          open_time: string
          slot_duration_minutes?: number
        }
        Update: {
          close_time?: string
          court_id?: string
          created_at?: string
          day_of_week?: number
          id?: string
          open_time?: string
          slot_duration_minutes?: number
        }
        Relationships: [
          {
            foreignKeyName: "court_availability_windows_court_id_fkey"
            columns: ["court_id"]
            isOneToOne: false
            referencedRelation: "courts"
            referencedColumns: ["id"]
          },
        ]
      }
      court_blackouts: {
        Row: {
          court_id: string
          created_at: string
          end_date: string
          id: string
          reason: string
          start_date: string
        }
        Insert: {
          court_id: string
          created_at?: string
          end_date: string
          id?: string
          reason: string
          start_date: string
        }
        Update: {
          court_id?: string
          created_at?: string
          end_date?: string
          id?: string
          reason?: string
          start_date?: string
        }
        Relationships: [
          {
            foreignKeyName: "court_blackouts_court_id_fkey"
            columns: ["court_id"]
            isOneToOne: false
            referencedRelation: "courts"
            referencedColumns: ["id"]
          },
        ]
      }
      court_bookings: {
        Row: {
          booking_source: Database["public"]["Enums"]["booking_source"]
          cancellation_reason: string | null
          checked_in_at: string | null
          court_id: string
          created_at: string
          created_by_staff_id: string | null
          date: string
          gst: number
          id: string
          payment_intent_id: string | null
          platform_fee: number
          rating: number | null
          remarks: string | null
          slot_end: string
          slot_start: string
          status: Database["public"]["Enums"]["court_booking_status"]
          subtotal: number
          total: number
          updated_at: string
          user_id: string | null
          walk_in_name: string | null
          walk_in_phone: string | null
        }
        Insert: {
          booking_source?: Database["public"]["Enums"]["booking_source"]
          cancellation_reason?: string | null
          checked_in_at?: string | null
          court_id: string
          created_at?: string
          created_by_staff_id?: string | null
          date: string
          gst: number
          id?: string
          payment_intent_id?: string | null
          platform_fee: number
          rating?: number | null
          remarks?: string | null
          slot_end: string
          slot_start: string
          status?: Database["public"]["Enums"]["court_booking_status"]
          subtotal: number
          total: number
          updated_at?: string
          user_id?: string | null
          walk_in_name?: string | null
          walk_in_phone?: string | null
        }
        Update: {
          booking_source?: Database["public"]["Enums"]["booking_source"]
          cancellation_reason?: string | null
          checked_in_at?: string | null
          court_id?: string
          created_at?: string
          created_by_staff_id?: string | null
          date?: string
          gst?: number
          id?: string
          payment_intent_id?: string | null
          platform_fee?: number
          rating?: number | null
          remarks?: string | null
          slot_end?: string
          slot_start?: string
          status?: Database["public"]["Enums"]["court_booking_status"]
          subtotal?: number
          total?: number
          updated_at?: string
          user_id?: string | null
          walk_in_name?: string | null
          walk_in_phone?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "court_bookings_court_id_fkey"
            columns: ["court_id"]
            isOneToOne: false
            referencedRelation: "courts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "court_bookings_created_by_staff_id_fkey"
            columns: ["created_by_staff_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "court_bookings_created_by_staff_id_fkey"
            columns: ["created_by_staff_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "court_bookings_payment_intent_id_fkey"
            columns: ["payment_intent_id"]
            isOneToOne: false
            referencedRelation: "payment_intents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "court_bookings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "court_bookings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      court_pricing_rules: {
        Row: {
          active: boolean
          court_id: string
          created_at: string
          day_of_week_end: number
          day_of_week_start: number
          fixed_price: number | null
          id: string
          multiplier: number | null
          time_end: string
          time_start: string
        }
        Insert: {
          active?: boolean
          court_id: string
          created_at?: string
          day_of_week_end: number
          day_of_week_start: number
          fixed_price?: number | null
          id?: string
          multiplier?: number | null
          time_end: string
          time_start: string
        }
        Update: {
          active?: boolean
          court_id?: string
          created_at?: string
          day_of_week_end?: number
          day_of_week_start?: number
          fixed_price?: number | null
          id?: string
          multiplier?: number | null
          time_end?: string
          time_start?: string
        }
        Relationships: [
          {
            foreignKeyName: "court_pricing_rules_court_id_fkey"
            columns: ["court_id"]
            isOneToOne: false
            referencedRelation: "courts"
            referencedColumns: ["id"]
          },
        ]
      }
      courts: {
        Row: {
          active: boolean
          base_price_per_hour: number
          capacity: number | null
          created_at: string
          id: string
          name: string
          sport: Database["public"]["Enums"]["sport"]
          updated_at: string
          venue_id: string
        }
        Insert: {
          active?: boolean
          base_price_per_hour: number
          capacity?: number | null
          created_at?: string
          id?: string
          name: string
          sport: Database["public"]["Enums"]["sport"]
          updated_at?: string
          venue_id: string
        }
        Update: {
          active?: boolean
          base_price_per_hour?: number
          capacity?: number | null
          created_at?: string
          id?: string
          name?: string
          sport?: Database["public"]["Enums"]["sport"]
          updated_at?: string
          venue_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "courts_venue_id_fkey"
            columns: ["venue_id"]
            isOneToOne: false
            referencedRelation: "venues"
            referencedColumns: ["id"]
          },
        ]
      }
      feature_flags: {
        Row: {
          created_at: string
          description: string
          enabled: boolean
          id: string
          key: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description: string
          enabled?: boolean
          id?: string
          key: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string
          enabled?: boolean
          id?: string
          key?: string
          updated_at?: string
        }
        Relationships: []
      }
      fee_config: {
        Row: {
          created_at: string
          domain: string
          effective_from: string
          id: string
          key: string
          value: number
          value_type: Database["public"]["Enums"]["fee_value_type"]
        }
        Insert: {
          created_at?: string
          domain: string
          effective_from?: string
          id?: string
          key: string
          value: number
          value_type: Database["public"]["Enums"]["fee_value_type"]
        }
        Update: {
          created_at?: string
          domain?: string
          effective_from?: string
          id?: string
          key?: string
          value?: number
          value_type?: Database["public"]["Enums"]["fee_value_type"]
        }
        Relationships: []
      }
      ledger_entries: {
        Row: {
          account_ref: string | null
          account_type: Database["public"]["Enums"]["ledger_account_type"]
          amount: number
          created_at: string
          description: string
          direction: Database["public"]["Enums"]["ledger_direction"]
          domain: Database["public"]["Enums"]["payment_domain"]
          entity_id: string
          entry_group_id: string
          id: string
          payment_intent_id: string | null
        }
        Insert: {
          account_ref?: string | null
          account_type: Database["public"]["Enums"]["ledger_account_type"]
          amount: number
          created_at?: string
          description: string
          direction: Database["public"]["Enums"]["ledger_direction"]
          domain: Database["public"]["Enums"]["payment_domain"]
          entity_id: string
          entry_group_id: string
          id?: string
          payment_intent_id?: string | null
        }
        Update: {
          account_ref?: string | null
          account_type?: Database["public"]["Enums"]["ledger_account_type"]
          amount?: number
          created_at?: string
          description?: string
          direction?: Database["public"]["Enums"]["ledger_direction"]
          domain?: Database["public"]["Enums"]["payment_domain"]
          entity_id?: string
          entry_group_id?: string
          id?: string
          payment_intent_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ledger_entries_payment_intent_id_fkey"
            columns: ["payment_intent_id"]
            isOneToOne: false
            referencedRelation: "payment_intents"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_prefs: {
        Row: {
          created_at: string
          email_enabled: boolean
          id: string
          notification_type: Database["public"]["Enums"]["notification_type"]
          push_enabled: boolean
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          email_enabled?: boolean
          id?: string
          notification_type: Database["public"]["Enums"]["notification_type"]
          push_enabled?: boolean
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          email_enabled?: boolean
          id?: string
          notification_type?: Database["public"]["Enums"]["notification_type"]
          push_enabled?: boolean
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notification_prefs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notification_prefs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string
          created_at: string
          deep_link: string
          id: string
          read_at: string | null
          title: string
          type: Database["public"]["Enums"]["notification_type"]
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          deep_link: string
          id?: string
          read_at?: string | null
          title: string
          type: Database["public"]["Enums"]["notification_type"]
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          deep_link?: string
          id?: string
          read_at?: string | null
          title?: string
          type?: Database["public"]["Enums"]["notification_type"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_intents: {
        Row: {
          amount: number
          created_at: string
          currency: string
          domain: Database["public"]["Enums"]["payment_domain"]
          entity_id: string | null
          id: string
          razorpay_order_id: string
          razorpay_payment_id: string | null
          status: Database["public"]["Enums"]["payment_intent_status"]
          updated_at: string
          user_id: string
        }
        Insert: {
          amount: number
          created_at?: string
          currency?: string
          domain: Database["public"]["Enums"]["payment_domain"]
          entity_id?: string | null
          id?: string
          razorpay_order_id: string
          razorpay_payment_id?: string | null
          status?: Database["public"]["Enums"]["payment_intent_status"]
          updated_at?: string
          user_id: string
        }
        Update: {
          amount?: number
          created_at?: string
          currency?: string
          domain?: Database["public"]["Enums"]["payment_domain"]
          entity_id?: string | null
          id?: string
          razorpay_order_id?: string
          razorpay_payment_id?: string | null
          status?: Database["public"]["Enums"]["payment_intent_status"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "payment_intents_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payment_intents_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      payout_accounts: {
        Row: {
          created_at: string
          id: string
          owner_id: string
          owner_type: string
          razorpay_account_id: string | null
          status: Database["public"]["Enums"]["payout_account_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          owner_id: string
          owner_type: string
          razorpay_account_id?: string | null
          status?: Database["public"]["Enums"]["payout_account_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          owner_id?: string
          owner_type?: string
          razorpay_account_id?: string | null
          status?: Database["public"]["Enums"]["payout_account_status"]
          updated_at?: string
        }
        Relationships: []
      }
      push_tokens: {
        Row: {
          created_at: string
          id: string
          platform: string
          token: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          platform: string
          token: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          platform?: string
          token?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "push_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      support_tickets: {
        Row: {
          created_at: string
          description: string
          id: string
          resolution_note: string | null
          resolved_at: string | null
          status: Database["public"]["Enums"]["ticket_status"]
          subject: string
          submitter_id: string
        }
        Insert: {
          created_at?: string
          description: string
          id?: string
          resolution_note?: string | null
          resolved_at?: string | null
          status?: Database["public"]["Enums"]["ticket_status"]
          subject: string
          submitter_id: string
        }
        Update: {
          created_at?: string
          description?: string
          id?: string
          resolution_note?: string | null
          resolved_at?: string | null
          status?: Database["public"]["Enums"]["ticket_status"]
          subject?: string
          submitter_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "support_tickets_submitter_id_fkey"
            columns: ["submitter_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "support_tickets_submitter_id_fkey"
            columns: ["submitter_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      transfers: {
        Row: {
          amount: number
          created_at: string
          id: string
          ledger_entry_group_id: string
          payout_account_id: string
          razorpay_transfer_id: string | null
          status: Database["public"]["Enums"]["transfer_status"]
        }
        Insert: {
          amount: number
          created_at?: string
          id?: string
          ledger_entry_group_id: string
          payout_account_id: string
          razorpay_transfer_id?: string | null
          status?: Database["public"]["Enums"]["transfer_status"]
        }
        Update: {
          amount?: number
          created_at?: string
          id?: string
          ledger_entry_group_id?: string
          payout_account_id?: string
          razorpay_transfer_id?: string | null
          status?: Database["public"]["Enums"]["transfer_status"]
        }
        Relationships: [
          {
            foreignKeyName: "transfers_payout_account_id_fkey"
            columns: ["payout_account_id"]
            isOneToOne: false
            referencedRelation: "payout_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      user_roles: {
        Row: {
          created_at: string
          id: string
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          role?: Database["public"]["Enums"]["app_role"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_roles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_roles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          avatar_url: string | null
          channel_name: string | null
          city: string | null
          created_at: string
          dob: string | null
          id: string
          name: string
          phone: string | null
          show_donor_name: boolean
          sports: Database["public"]["Enums"]["sport"][]
          state: string | null
          status: Database["public"]["Enums"]["user_status"]
          suspended_reason: string | null
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          channel_name?: string | null
          city?: string | null
          created_at?: string
          dob?: string | null
          id: string
          name: string
          phone?: string | null
          show_donor_name?: boolean
          sports?: Database["public"]["Enums"]["sport"][]
          state?: string | null
          status?: Database["public"]["Enums"]["user_status"]
          suspended_reason?: string | null
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          channel_name?: string | null
          city?: string | null
          created_at?: string
          dob?: string | null
          id?: string
          name?: string
          phone?: string | null
          show_donor_name?: boolean
          sports?: Database["public"]["Enums"]["sport"][]
          state?: string | null
          status?: Database["public"]["Enums"]["user_status"]
          suspended_reason?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      venue_photos: {
        Row: {
          created_at: string
          id: string
          position: number
          storage_path: string
          venue_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          position?: number
          storage_path: string
          venue_id: string
        }
        Update: {
          created_at?: string
          id?: string
          position?: number
          storage_path?: string
          venue_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "venue_photos_venue_id_fkey"
            columns: ["venue_id"]
            isOneToOne: false
            referencedRelation: "venues"
            referencedColumns: ["id"]
          },
        ]
      }
      venue_staff: {
        Row: {
          accepted_at: string | null
          id: string
          invited_at: string
          user_id: string
          venue_id: string
        }
        Insert: {
          accepted_at?: string | null
          id?: string
          invited_at?: string
          user_id: string
          venue_id: string
        }
        Update: {
          accepted_at?: string | null
          id?: string
          invited_at?: string
          user_id?: string
          venue_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "venue_staff_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "venue_staff_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "venue_staff_venue_id_fkey"
            columns: ["venue_id"]
            isOneToOne: false
            referencedRelation: "venues"
            referencedColumns: ["id"]
          },
        ]
      }
      venues: {
        Row: {
          address: string
          city: string
          created_at: string
          description: string | null
          id: string
          lat: number | null
          lng: number | null
          name: string
          partner_user_id: string
          pincode: string
          rejection_reason: string | null
          status: Database["public"]["Enums"]["venue_status"]
          updated_at: string
        }
        Insert: {
          address: string
          city: string
          created_at?: string
          description?: string | null
          id?: string
          lat?: number | null
          lng?: number | null
          name: string
          partner_user_id: string
          pincode: string
          rejection_reason?: string | null
          status?: Database["public"]["Enums"]["venue_status"]
          updated_at?: string
        }
        Update: {
          address?: string
          city?: string
          created_at?: string
          description?: string | null
          id?: string
          lat?: number | null
          lng?: number | null
          name?: string
          partner_user_id?: string
          pincode?: string
          rejection_reason?: string | null
          status?: Database["public"]["Enums"]["venue_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "venues_partner_user_id_fkey"
            columns: ["partner_user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "venues_partner_user_id_fkey"
            columns: ["partner_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      verification_requests: {
        Row: {
          applicant_id: string
          applicant_type: Database["public"]["Enums"]["applicant_type"]
          created_at: string
          id: string
          payload: Json
          rejection_reason: string | null
          reviewed_at: string | null
          reviewer_id: string | null
          status: Database["public"]["Enums"]["verification_status"]
        }
        Insert: {
          applicant_id: string
          applicant_type: Database["public"]["Enums"]["applicant_type"]
          created_at?: string
          id?: string
          payload: Json
          rejection_reason?: string | null
          reviewed_at?: string | null
          reviewer_id?: string | null
          status?: Database["public"]["Enums"]["verification_status"]
        }
        Update: {
          applicant_id?: string
          applicant_type?: Database["public"]["Enums"]["applicant_type"]
          created_at?: string
          id?: string
          payload?: Json
          rejection_reason?: string | null
          reviewed_at?: string | null
          reviewer_id?: string | null
          status?: Database["public"]["Enums"]["verification_status"]
        }
        Relationships: [
          {
            foreignKeyName: "verification_requests_reviewer_id_fkey"
            columns: ["reviewer_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "verification_requests_reviewer_id_fkey"
            columns: ["reviewer_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      webhook_events: {
        Row: {
          event_type: string
          id: string
          payload: Json
          processed_at: string
        }
        Insert: {
          event_type: string
          id: string
          payload: Json
          processed_at?: string
        }
        Update: {
          event_type?: string
          id?: string
          payload?: Json
          processed_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      coach_profiles_public: {
        Row: {
          bio: string | null
          city: string | null
          coaching_style: string | null
          created_at: string | null
          experience_years: number | null
          players_coached_count: number | null
          rating: number | null
          rating_count: number | null
          specialization: string[] | null
          sport: Database["public"]["Enums"]["sport"] | null
          state: string | null
          user_id: string | null
        }
        Insert: {
          bio?: string | null
          city?: string | null
          coaching_style?: string | null
          created_at?: string | null
          experience_years?: number | null
          players_coached_count?: number | null
          rating?: number | null
          rating_count?: number | null
          specialization?: string[] | null
          sport?: Database["public"]["Enums"]["sport"] | null
          state?: string | null
          user_id?: string | null
        }
        Update: {
          bio?: string | null
          city?: string | null
          coaching_style?: string | null
          created_at?: string | null
          experience_years?: number | null
          players_coached_count?: number | null
          rating?: number | null
          rating_count?: number | null
          specialization?: string[] | null
          sport?: Database["public"]["Enums"]["sport"] | null
          state?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "coach_profiles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "coach_profiles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      public_profiles: {
        Row: {
          avatar_url: string | null
          channel_name: string | null
          id: string | null
          name: string | null
        }
        Insert: {
          avatar_url?: string | null
          channel_name?: string | null
          id?: string | null
          name?: string | null
        }
        Update: {
          avatar_url?: string | null
          channel_name?: string | null
          id?: string | null
          name?: string | null
        }
        Relationships: []
      }
      venue_bookings_today: {
        Row: {
          booking_source: Database["public"]["Enums"]["booking_source"] | null
          cancellation_reason: string | null
          checked_in_at: string | null
          court_id: string | null
          court_name: string | null
          court_sport: Database["public"]["Enums"]["sport"] | null
          created_at: string | null
          created_by_staff_id: string | null
          date: string | null
          gst: number | null
          id: string | null
          payment_intent_id: string | null
          platform_fee: number | null
          rating: number | null
          remarks: string | null
          slot_end: string | null
          slot_start: string | null
          status: Database["public"]["Enums"]["court_booking_status"] | null
          subtotal: number | null
          total: number | null
          updated_at: string | null
          user_id: string | null
          venue_id: string | null
          walk_in_name: string | null
          walk_in_phone: string | null
        }
        Relationships: [
          {
            foreignKeyName: "court_bookings_court_id_fkey"
            columns: ["court_id"]
            isOneToOne: false
            referencedRelation: "courts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "court_bookings_created_by_staff_id_fkey"
            columns: ["created_by_staff_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "court_bookings_created_by_staff_id_fkey"
            columns: ["created_by_staff_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "court_bookings_payment_intent_id_fkey"
            columns: ["payment_intent_id"]
            isOneToOne: false
            referencedRelation: "payment_intents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "court_bookings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "court_bookings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "courts_venue_id_fkey"
            columns: ["venue_id"]
            isOneToOne: false
            referencedRelation: "venues"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      accept_venue_staff_invite: {
        Args: { p_venue_staff_id: string }
        Returns: {
          accepted_at: string | null
          id: string
          invited_at: string
          user_id: string
          venue_id: string
        }
        SetofOptions: {
          from: "*"
          to: "venue_staff"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      admin_approve_verification_request: {
        Args: { p_request_id: string }
        Returns: {
          applicant_id: string
          applicant_type: Database["public"]["Enums"]["applicant_type"]
          created_at: string
          id: string
          payload: Json
          rejection_reason: string | null
          reviewed_at: string | null
          reviewer_id: string | null
          status: Database["public"]["Enums"]["verification_status"]
        }
        SetofOptions: {
          from: "*"
          to: "verification_requests"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      admin_reject_verification_request: {
        Args: { p_reason: string; p_request_id: string }
        Returns: {
          applicant_id: string
          applicant_type: Database["public"]["Enums"]["applicant_type"]
          created_at: string
          id: string
          payload: Json
          rejection_reason: string | null
          reviewed_at: string | null
          reviewer_id: string | null
          status: Database["public"]["Enums"]["verification_status"]
        }
        SetofOptions: {
          from: "*"
          to: "verification_requests"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      admin_update_fee_config: {
        Args: { p_id: string; p_note: string; p_value: number }
        Returns: {
          created_at: string
          domain: string
          effective_from: string
          id: string
          key: string
          value: number
          value_type: Database["public"]["Enums"]["fee_value_type"]
        }
        SetofOptions: {
          from: "*"
          to: "fee_config"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      complete_player_setup: {
        Args: {
          p_avatar_url: string
          p_city: string
          p_sports: Database["public"]["Enums"]["sport"][]
          p_state: string
        }
        Returns: undefined
      }
      court_booking_check_in: {
        Args: { p_booking_id: string }
        Returns: {
          booking_source: Database["public"]["Enums"]["booking_source"]
          cancellation_reason: string | null
          checked_in_at: string | null
          court_id: string
          created_at: string
          created_by_staff_id: string | null
          date: string
          gst: number
          id: string
          payment_intent_id: string | null
          platform_fee: number
          rating: number | null
          remarks: string | null
          slot_end: string
          slot_start: string
          status: Database["public"]["Enums"]["court_booking_status"]
          subtotal: number
          total: number
          updated_at: string
          user_id: string | null
          walk_in_name: string | null
          walk_in_phone: string | null
        }
        SetofOptions: {
          from: "*"
          to: "court_bookings"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      court_booking_confirm_payment: {
        Args: { p_booking_id: string; p_payment_intent_id: string }
        Returns: {
          booking_source: Database["public"]["Enums"]["booking_source"]
          cancellation_reason: string | null
          checked_in_at: string | null
          court_id: string
          created_at: string
          created_by_staff_id: string | null
          date: string
          gst: number
          id: string
          payment_intent_id: string | null
          platform_fee: number
          rating: number | null
          remarks: string | null
          slot_end: string
          slot_start: string
          status: Database["public"]["Enums"]["court_booking_status"]
          subtotal: number
          total: number
          updated_at: string
          user_id: string | null
          walk_in_name: string | null
          walk_in_phone: string | null
        }
        SetofOptions: {
          from: "*"
          to: "court_bookings"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      court_booking_expire_payment: {
        Args: { p_booking_id: string }
        Returns: {
          booking_source: Database["public"]["Enums"]["booking_source"]
          cancellation_reason: string | null
          checked_in_at: string | null
          court_id: string
          created_at: string
          created_by_staff_id: string | null
          date: string
          gst: number
          id: string
          payment_intent_id: string | null
          platform_fee: number
          rating: number | null
          remarks: string | null
          slot_end: string
          slot_start: string
          status: Database["public"]["Enums"]["court_booking_status"]
          subtotal: number
          total: number
          updated_at: string
          user_id: string | null
          walk_in_name: string | null
          walk_in_phone: string | null
        }
        SetofOptions: {
          from: "*"
          to: "court_bookings"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      court_booking_transition: {
        Args: {
          p_action: string
          p_booking_id: string
          p_new_date?: string
          p_new_slot_start?: string
          p_reason?: string
        }
        Returns: {
          booking_source: Database["public"]["Enums"]["booking_source"]
          cancellation_reason: string | null
          checked_in_at: string | null
          court_id: string
          created_at: string
          created_by_staff_id: string | null
          date: string
          gst: number
          id: string
          payment_intent_id: string | null
          platform_fee: number
          rating: number | null
          remarks: string | null
          slot_end: string
          slot_start: string
          status: Database["public"]["Enums"]["court_booking_status"]
          subtotal: number
          total: number
          updated_at: string
          user_id: string | null
          walk_in_name: string | null
          walk_in_phone: string | null
        }
        SetofOptions: {
          from: "*"
          to: "court_bookings"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      custom_access_token_hook: { Args: { event: Json }; Returns: Json }
      get_court_available_slots: {
        Args: { p_court_id: string; p_date: string }
        Returns: {
          price: number
          slot_end: string
          slot_start: string
        }[]
      }
      get_court_busy_slots: {
        Args: { p_court_id: string; p_from: string; p_to: string }
        Returns: {
          date: string
          slot_start: string
        }[]
      }
      get_court_rating_summary: {
        Args: { p_court_id: string }
        Returns: {
          rating: number
          rating_count: number
        }[]
      }
      has_role: { Args: { _role: string }; Returns: boolean }
      is_admin: { Args: never; Returns: boolean }
      is_court_partner_or_staff: {
        Args: { p_court_id: string }
        Returns: boolean
      }
      is_guest: { Args: never; Returns: boolean }
      is_moderator: { Args: never; Returns: boolean }
      rate_court_booking: {
        Args: { p_booking_id: string; p_rating: number; p_remarks?: string }
        Returns: {
          booking_source: Database["public"]["Enums"]["booking_source"]
          cancellation_reason: string | null
          checked_in_at: string | null
          court_id: string
          created_at: string
          created_by_staff_id: string | null
          date: string
          gst: number
          id: string
          payment_intent_id: string | null
          platform_fee: number
          rating: number | null
          remarks: string | null
          slot_end: string
          slot_start: string
          status: Database["public"]["Enums"]["court_booking_status"]
          subtotal: number
          total: number
          updated_at: string
          user_id: string | null
          walk_in_name: string | null
          walk_in_phone: string | null
        }
        SetofOptions: {
          from: "*"
          to: "court_bookings"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      submit_coach_verification: { Args: { p_payload: Json }; Returns: string }
      submit_venue_verification: { Args: { p_payload: Json }; Returns: string }
      timemultirange: { Args: never; Returns: unknown }
    }
    Enums: {
      app_role:
        | "player"
        | "coach"
        | "court_partner"
        | "court_staff"
        | "upa"
        | "admin"
        | "moderator"
      applicant_type: "coach" | "venue" | "upa"
      booking_source: "self_service" | "walk_in"
      coach_status: "pending_review" | "verified" | "rejected"
      court_booking_status:
        | "confirmed"
        | "completed"
        | "cancelled"
        | "rescheduled"
        | "no_show"
        | "pending_payment"
        | "expired"
      fee_value_type: "percentage" | "flat"
      ledger_account_type:
        | "platform"
        | "coach"
        | "court_partner"
        | "upa_fund"
        | "user"
      ledger_direction: "debit" | "credit"
      notification_type:
        | "booking"
        | "order"
        | "chat"
        | "clip_moderation"
        | "donation"
        | "verification"
        | "transfer"
        | "support"
      payment_domain: "session" | "court" | "commerce" | "donation"
      payment_intent_status:
        | "created"
        | "authorized"
        | "captured"
        | "failed"
        | "refunded"
        | "partially_refunded"
      payout_account_status:
        | "not_started"
        | "pending"
        | "active"
        | "needs_attention"
        | "failed"
      sport: "football" | "cricket" | "badminton" | "tennis"
      ticket_status: "open" | "resolved"
      transfer_status: "processing" | "paid" | "failed"
      user_status: "active" | "suspended"
      venue_status: "pending" | "verified" | "rejected"
      verification_status: "pending_review" | "approved" | "rejected"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      app_role: [
        "player",
        "coach",
        "court_partner",
        "court_staff",
        "upa",
        "admin",
        "moderator",
      ],
      applicant_type: ["coach", "venue", "upa"],
      booking_source: ["self_service", "walk_in"],
      coach_status: ["pending_review", "verified", "rejected"],
      court_booking_status: [
        "confirmed",
        "completed",
        "cancelled",
        "rescheduled",
        "no_show",
        "pending_payment",
        "expired",
      ],
      fee_value_type: ["percentage", "flat"],
      ledger_account_type: [
        "platform",
        "coach",
        "court_partner",
        "upa_fund",
        "user",
      ],
      ledger_direction: ["debit", "credit"],
      notification_type: [
        "booking",
        "order",
        "chat",
        "clip_moderation",
        "donation",
        "verification",
        "transfer",
        "support",
      ],
      payment_domain: ["session", "court", "commerce", "donation"],
      payment_intent_status: [
        "created",
        "authorized",
        "captured",
        "failed",
        "refunded",
        "partially_refunded",
      ],
      payout_account_status: [
        "not_started",
        "pending",
        "active",
        "needs_attention",
        "failed",
      ],
      sport: ["football", "cricket", "badminton", "tennis"],
      ticket_status: ["open", "resolved"],
      transfer_status: ["processing", "paid", "failed"],
      user_status: ["active", "suspended"],
      venue_status: ["pending", "verified", "rejected"],
      verification_status: ["pending_review", "approved", "rejected"],
    },
  },
} as const
