// GENERATED by `supabase gen types typescript` (via the Supabase MCP
// generate_typescript_types tool) against the `atlitos` project
// (syzzfgaudpifwvbpycyi) after migrations 0001-0006 were applied. Covers the
// identity/roles, notifications, and moderation/audit domains plus the
// Phase 1 onboarding RPCs (0004_player_and_coach_setup_rpc.sql). Every later
// domain migration (coaching's session_types/coach_availability_windows,
// courts, commerce, clutch, empower, learn, chat, payments) regenerates this
// file wholesale when it lands; do not hand-edit it, re-run generation
// instead. `db/rows.ts` in this package documents the eventual full schema
// (including domains not yet migrated) and is what app code should still
// prefer importing from for domains this file does not cover yet.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      addresses: {
        Row: {
          city: string;
          created_at: string;
          id: string;
          is_default: boolean;
          line1: string;
          line2: string | null;
          pincode: string;
          state: string;
          user_id: string;
        };
        Insert: {
          city: string;
          created_at?: string;
          id?: string;
          is_default?: boolean;
          line1: string;
          line2?: string | null;
          pincode: string;
          state: string;
          user_id: string;
        };
        Update: {
          city?: string;
          created_at?: string;
          id?: string;
          is_default?: boolean;
          line1?: string;
          line2?: string | null;
          pincode?: string;
          state?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "addresses_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "addresses_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      athlete_sports: {
        Row: {
          created_at: string;
          id: string;
          is_primary: boolean;
          skill_level: string | null;
          sport: Database["public"]["Enums"]["sport"];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          is_primary?: boolean;
          skill_level?: string | null;
          sport: Database["public"]["Enums"]["sport"];
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          is_primary?: boolean;
          skill_level?: string | null;
          sport?: Database["public"]["Enums"]["sport"];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "athlete_sports_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "athlete_sports_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_log: {
        Row: {
          action: string;
          actor_id: string | null;
          after: Json | null;
          before: Json | null;
          created_at: string;
          entity_id: string;
          entity_type: string;
          id: string;
          note: string | null;
        };
        Insert: {
          action: string;
          actor_id?: string | null;
          after?: Json | null;
          before?: Json | null;
          created_at?: string;
          entity_id: string;
          entity_type: string;
          id?: string;
          note?: string | null;
        };
        Update: {
          action?: string;
          actor_id?: string | null;
          after?: Json | null;
          before?: Json | null;
          created_at?: string;
          entity_id?: string;
          entity_type?: string;
          id?: string;
          note?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "audit_log_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      coach_certificates: {
        Row: {
          coach_id: string;
          created_at: string;
          id: string;
          name: string;
          storage_path: string;
          verified: boolean;
        };
        Insert: {
          coach_id: string;
          created_at?: string;
          id?: string;
          name: string;
          storage_path: string;
          verified?: boolean;
        };
        Update: {
          coach_id?: string;
          created_at?: string;
          id?: string;
          name?: string;
          storage_path?: string;
          verified?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "coach_certificates_coach_id_fkey";
            columns: ["coach_id"];
            isOneToOne: false;
            referencedRelation: "coach_profiles";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "coach_certificates_coach_id_fkey";
            columns: ["coach_id"];
            isOneToOne: false;
            referencedRelation: "coach_profiles_public";
            referencedColumns: ["user_id"];
          },
        ];
      };
      coach_profiles: {
        Row: {
          bio: string | null;
          city: string;
          coaching_style: string | null;
          created_at: string;
          experience_years: number;
          players_coached_count: number;
          rating: number;
          rating_count: number;
          specialization: string[];
          sport: Database["public"]["Enums"]["sport"];
          state: string;
          status: Database["public"]["Enums"]["coach_status"];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          bio?: string | null;
          city: string;
          coaching_style?: string | null;
          created_at?: string;
          experience_years: number;
          players_coached_count?: number;
          rating?: number;
          rating_count?: number;
          specialization?: string[];
          sport: Database["public"]["Enums"]["sport"];
          state: string;
          status?: Database["public"]["Enums"]["coach_status"];
          updated_at?: string;
          user_id: string;
        };
        Update: {
          bio?: string | null;
          city?: string;
          coaching_style?: string | null;
          created_at?: string;
          experience_years?: number;
          players_coached_count?: number;
          rating?: number;
          rating_count?: number;
          specialization?: string[];
          sport?: Database["public"]["Enums"]["sport"];
          state?: string;
          status?: Database["public"]["Enums"]["coach_status"];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "coach_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "public_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "coach_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      feature_flags: {
        Row: {
          created_at: string;
          description: string;
          enabled: boolean;
          id: string;
          key: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          description: string;
          enabled?: boolean;
          id?: string;
          key: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          description?: string;
          enabled?: boolean;
          id?: string;
          key?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notification_prefs: {
        Row: {
          created_at: string;
          email_enabled: boolean;
          id: string;
          notification_type: Database["public"]["Enums"]["notification_type"];
          push_enabled: boolean;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          email_enabled?: boolean;
          id?: string;
          notification_type: Database["public"]["Enums"]["notification_type"];
          push_enabled?: boolean;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          email_enabled?: boolean;
          id?: string;
          notification_type?: Database["public"]["Enums"]["notification_type"];
          push_enabled?: boolean;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notification_prefs_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notification_prefs_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      notifications: {
        Row: {
          body: string;
          created_at: string;
          deep_link: string;
          id: string;
          read_at: string | null;
          title: string;
          type: Database["public"]["Enums"]["notification_type"];
          user_id: string;
        };
        Insert: {
          body: string;
          created_at?: string;
          deep_link: string;
          id?: string;
          read_at?: string | null;
          title: string;
          type: Database["public"]["Enums"]["notification_type"];
          user_id: string;
        };
        Update: {
          body?: string;
          created_at?: string;
          deep_link?: string;
          id?: string;
          read_at?: string | null;
          title?: string;
          type?: Database["public"]["Enums"]["notification_type"];
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notifications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      push_tokens: {
        Row: {
          created_at: string;
          id: string;
          platform: string;
          token: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          platform: string;
          token: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          platform?: string;
          token?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "push_tokens_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "push_tokens_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      support_tickets: {
        Row: {
          created_at: string;
          description: string;
          id: string;
          resolution_note: string | null;
          resolved_at: string | null;
          status: Database["public"]["Enums"]["ticket_status"];
          subject: string;
          submitter_id: string;
        };
        Insert: {
          created_at?: string;
          description: string;
          id?: string;
          resolution_note?: string | null;
          resolved_at?: string | null;
          status?: Database["public"]["Enums"]["ticket_status"];
          subject: string;
          submitter_id: string;
        };
        Update: {
          created_at?: string;
          description?: string;
          id?: string;
          resolution_note?: string | null;
          resolved_at?: string | null;
          status?: Database["public"]["Enums"]["ticket_status"];
          subject?: string;
          submitter_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "support_tickets_submitter_id_fkey";
            columns: ["submitter_id"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "support_tickets_submitter_id_fkey";
            columns: ["submitter_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      user_roles: {
        Row: {
          created_at: string;
          id: string;
          role: Database["public"]["Enums"]["app_role"];
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          role: Database["public"]["Enums"]["app_role"];
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          role?: Database["public"]["Enums"]["app_role"];
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_roles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "user_roles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      users: {
        Row: {
          avatar_url: string | null;
          channel_name: string | null;
          city: string | null;
          created_at: string;
          dob: string | null;
          id: string;
          name: string;
          phone: string | null;
          show_donor_name: boolean;
          sports: Database["public"]["Enums"]["sport"][];
          state: string | null;
          status: Database["public"]["Enums"]["user_status"];
          suspended_reason: string | null;
          updated_at: string;
        };
        Insert: {
          avatar_url?: string | null;
          channel_name?: string | null;
          city?: string | null;
          created_at?: string;
          dob?: string | null;
          id: string;
          name: string;
          phone?: string | null;
          show_donor_name?: boolean;
          sports?: Database["public"]["Enums"]["sport"][];
          state?: string | null;
          status?: Database["public"]["Enums"]["user_status"];
          suspended_reason?: string | null;
          updated_at?: string;
        };
        Update: {
          avatar_url?: string | null;
          channel_name?: string | null;
          city?: string | null;
          created_at?: string;
          dob?: string | null;
          id?: string;
          name?: string;
          phone?: string | null;
          show_donor_name?: boolean;
          sports?: Database["public"]["Enums"]["sport"][];
          state?: string | null;
          status?: Database["public"]["Enums"]["user_status"];
          suspended_reason?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      verification_requests: {
        Row: {
          applicant_id: string;
          applicant_type: Database["public"]["Enums"]["applicant_type"];
          created_at: string;
          id: string;
          payload: Json;
          rejection_reason: string | null;
          reviewed_at: string | null;
          reviewer_id: string | null;
          status: Database["public"]["Enums"]["verification_status"];
        };
        Insert: {
          applicant_id: string;
          applicant_type: Database["public"]["Enums"]["applicant_type"];
          created_at?: string;
          id?: string;
          payload: Json;
          rejection_reason?: string | null;
          reviewed_at?: string | null;
          reviewer_id?: string | null;
          status?: Database["public"]["Enums"]["verification_status"];
        };
        Update: {
          applicant_id?: string;
          applicant_type?: Database["public"]["Enums"]["applicant_type"];
          created_at?: string;
          id?: string;
          payload?: Json;
          rejection_reason?: string | null;
          reviewed_at?: string | null;
          reviewer_id?: string | null;
          status?: Database["public"]["Enums"]["verification_status"];
        };
        Relationships: [
          {
            foreignKeyName: "verification_requests_reviewer_id_fkey";
            columns: ["reviewer_id"];
            isOneToOne: false;
            referencedRelation: "public_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "verification_requests_reviewer_id_fkey";
            columns: ["reviewer_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      coach_profiles_public: {
        Row: {
          bio: string | null;
          city: string | null;
          coaching_style: string | null;
          created_at: string | null;
          experience_years: number | null;
          players_coached_count: number | null;
          rating: number | null;
          rating_count: number | null;
          specialization: string[] | null;
          sport: Database["public"]["Enums"]["sport"] | null;
          state: string | null;
          user_id: string | null;
        };
        Insert: {
          bio?: string | null;
          city?: string | null;
          coaching_style?: string | null;
          created_at?: string | null;
          experience_years?: number | null;
          players_coached_count?: number | null;
          rating?: number | null;
          rating_count?: number | null;
          specialization?: string[] | null;
          sport?: Database["public"]["Enums"]["sport"] | null;
          state?: string | null;
          user_id?: string | null;
        };
        Update: {
          bio?: string | null;
          city?: string | null;
          coaching_style?: string | null;
          created_at?: string | null;
          experience_years?: number | null;
          players_coached_count?: number | null;
          rating?: number | null;
          rating_count?: number | null;
          specialization?: string[] | null;
          sport?: Database["public"]["Enums"]["sport"] | null;
          state?: string | null;
          user_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "coach_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "public_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "coach_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      public_profiles: {
        Row: {
          avatar_url: string | null;
          channel_name: string | null;
          id: string | null;
          name: string | null;
        };
        Insert: {
          avatar_url?: string | null;
          channel_name?: string | null;
          id?: string | null;
          name?: string | null;
        };
        Update: {
          avatar_url?: string | null;
          channel_name?: string | null;
          id?: string | null;
          name?: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      complete_player_setup: {
        Args: {
          p_avatar_url: string;
          p_city: string;
          p_sports: Database["public"]["Enums"]["sport"][];
          p_state: string;
        };
        Returns: undefined;
      };
      custom_access_token_hook: { Args: { event: Json }; Returns: Json };
      has_role: { Args: { _role: string }; Returns: boolean };
      is_admin: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_guest: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_moderator: { Args: Record<PropertyKey, never>; Returns: boolean };
      submit_coach_verification: { Args: { p_payload: Json }; Returns: string };
    };
    Enums: {
      app_role: "player" | "coach" | "court_partner" | "court_staff" | "upa" | "admin" | "moderator";
      applicant_type: "coach" | "venue" | "upa";
      coach_status: "pending_review" | "verified" | "rejected";
      notification_type:
        | "booking"
        | "order"
        | "chat"
        | "clip_moderation"
        | "donation"
        | "verification"
        | "transfer"
        | "support";
      sport: "football" | "cricket" | "badminton" | "tennis";
      ticket_status: "open" | "resolved";
      user_status: "active" | "suspended";
      verification_status: "pending_review" | "approved" | "rejected";
    };
    CompositeTypes: Record<string, never>;
  };
};
