-- 0064_advisor_function_search_path.sql
-- AT-140: function_search_path_mutable burn-down (14 WARN -> 5 residual, by design).
--
-- Pin a stable, empty search_path on each flagged application function so name
-- resolution inside the body cannot be hijacked by a caller-controlled
-- search_path. Every one of these references its objects either fully
-- schema-qualified (public.*, auth.*) or not at all (pure jsonb / NEW-OLD /
-- pg_catalog casts), so search_path = '' changes NO behaviour; it only removes
-- the mutable-path lint. ALTER FUNCTION SET config does not touch the body,
-- grants, or security attributes (none are SECURITY DEFINER; the custom access
-- token hook keeps its supabase_auth_admin grant untouched, per RLS.md 0017).
--
-- RESIDUAL, KEEP by design (dispositioned in RLS.md): the 5 flagged
-- timerange()/timemultirange() entries are the constructor functions auto-
-- generated by the `timerange` custom range type. They are owned by
-- supabase_admin (not by the app), so the app migration role cannot ALTER them,
-- and they are `internal` C constructors with no SQL body and no
-- search_path-sensitive name resolution, so the mutable-path finding is inert
-- for them. They are left as-is.

alter function public.audit_changed_fields(jsonb, jsonb) set search_path = '';
alter function public.custom_access_token_hook(jsonb) set search_path = '';
alter function public.is_admin() set search_path = '';
alter function public.is_guest() set search_path = '';
alter function public.is_moderator() set search_path = '';
alter function public.lock_coach_sport_after_submission() set search_path = '';
alter function public.lock_notification_fields() set search_path = '';
alter function public.set_updated_at() set search_path = '';
alter function public.unpaid_hold_ttl() set search_path = '';
