-- ATLITOS v2 — 0088_notification_types_coaching.sql
-- Domain: notifications. Adds the two notification_type values coaching has
-- been missing since 0002.
--
-- WHY THIS IS ITS OWN MIGRATION, and why it contains nothing else: Postgres
-- refuses to USE an enum value in the same transaction that added it. The
-- Supabase CLI runs each migration file in one transaction, so the ADD VALUE
-- must commit before 0089 and 0090 can write a notifications row carrying it.
-- 0076 header note 6 made the same split for payment_domain 'membership'.
--
-- The gap being closed: notification_type (0002_notifications.sql) is
-- ('booking','order','chat','clip_moderation','donation','verification',
-- 'transfer','support'). There is no value for anything that happens to a
-- coaching session or to a group membership, which is why NOTHING in the
-- coaching domain has ever been able to notify anyone. 'booking' was not
-- reused for either: it means a court booking everywhere else in the product
-- (finalize-court-booking-payment.ts is its only writer), and notification
-- prefs are per type, so folding sessions into it would mean an athlete
-- muting court receipts also silently muted their coach accepting a session.
--
--   'session'    a coaching session changed state: accepted, declined,
--                started or completed (emitted in 0089).
--   'membership' a group membership is about to end, has ended, or has
--                lapsed (emitted by the sweep in 0090).
--
-- Mirrors updated in the same change: packages/types/src/enums.ts
-- NOTIFICATION_TYPES, supabase/functions/_shared/notify.ts NOTIFICATION_TYPES,
-- apps/mobile/src/lib/notification-display.ts DISPLAY.

alter type public.notification_type add value if not exists 'session';
alter type public.notification_type add value if not exists 'membership';
